server:
  port: 8088


spring:
  profiles:
    active: default
  thymeleaf:
     cache: false
     encoding: UTF-8
     content-type: text/html
     mode: HTML5


---
spring:
  profiles: default

logging:
 level:
  root: INFO
  org.springframework: WARN
  org.mybatis: WARN
  com.journey.thymeleaf: Debug