server:
  port: 8089

spring:
  profiles:
    active: default

---

spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/journey_mybatis?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true    #是否开启sql的log 默认为 false





logging:
  level:
      root: INFO
      org.springframework: WARN
      org.hibernate: WARN
      com.journey.thymeleaf: Debug